title: Lu He
url: "https://ankitsultana.com"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "mailto:he32@uwm.edu"
footer_text: "Email"
footer_url_GoogleScholar: "https://scholar.google.com/citations?user=AhFagYAAAAAJ&hl=en&authuser=2"
footer_text_GoogleScholar: "Google Scholar"
footer_url_Email: ""
footer_text_Email: ""
footer_url_source: ""
footer_text_source: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Publications"
   link: "publications"
 - name: "Teaching"
   link: "teaching"
 - name: "Group"
   link: "group"
 - name: "Misc"
   link: "misc"
