title: Lu He
url: "https://ankitsultana.com"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: [Email](mailto:you@example.com) | [Google Scholar](https://scholar.google.com/citations?user=XXXXX) | [LinkedIn](https://www.linkedin.com/in/yourprofile/) | Site built with [Jekyll](https://jekyllrb.com/), template [here](https://github.com/your-template)

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "CV"
   link: "resume.pdf"
 - name: "Publications"
   link: "publications"
 - name: "Group"
   link: "group"
 - name: "Contact"
   link: "contact"
